name: Virtual Financial
favicon: null
layout_spectrum: 0.0176740565802902
typography_spectrum: 0.016528282314538956
title: Conviction Pay to The Tune of 6 and 7  Figures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#25b867'
    - '#fe9100'
    - '#732b10'
    - '#3a4ae8'
  brandStrength: 0.9711746277753264
  lightness: 0.02751490054652095
  saturation: 0.9901903953868896
  rhythmicContrast: 0.7239272859878838
purpose: []
